version: '3'
services:
  web:
    build: 
      context: vdt-frontend
      dockerfile: Dockerfile
    image: qdgiang/vdt_frontend
    ports:
      - 80:80
    networks:
      - vdt_network
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower

networks:
  vdt_network:
    name: vdt_network
    external: true
      
    